name: check_ios
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  check_ios:
    runs-on: macos-13
    timeout-minutes: 20
    steps:
      - run: sudo xcode-select -s '/Applications/Xcode_15.0.1.app/Contents/Developer'
      - run: xcodebuild -version
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: irgaly/setup-mint@v1
      # フォーマットチェック
      - run: mint run swiftformat --lint .
